states = [
    "Arkansas"
    "Iowa"
    "Idaho"
    "Alabama"
    "Arizona"
    "Illinois"
    "Indiana"
    "Wisconsin"
    "West Virginia"
    "Oklahoma"
    "Ohio"
    "Oregon"
    "California"
    "Kansas"
    "Kentucky"
    "Connecticut"
    "Colorado"
    "South Carolin"
    "South Dakotaa"
    "Georgia"
    "Texas"
    "Tennessee"
    "Delaware"
    "New Jersey	"
    "New Hampshire"
    "New Mexico"
    "New York"
    "Nevada"
    "Nebraska"
    "North Carolina"
    "North Dakota"
    "Virginia"
    "Vermont"
    "Florida"
    "Pennsylvania"
    "Massachusetts"
    "Michigan"
    "Mississippi"
    "Missouri"
    "Minnesota"
    "Maine"
    "Maryland"
    "Montana"
    "Utah"
    "Louisiana"
    "Rhode Island"
    "Wyoming"
    "Washington"
]
with open("./states.txt","wb")as f:
    